### ISSUE TITLE
Implement a way to create menus

### ISSUE THREAD

**Issue by SiXoS** [Bubbad/Bubba-3D#31]
A menu is quite vital for a game to work as expected. Some research needs to be done on how the menus should be cunstructed. 
- It might be possible to do the menu in HTML. Then it would be easy to make the design and connect click listeners. However, HTML doesn't have native support for sliders and other useful input types.
- Other methods should be researched

**Comment by DunderRoffe** [comment]
Use camera objects as an IComponent and rotate / move the GameObject it is attached to
