### ISSUE TITLE
Structure CMAKE for tests

### ISSUE THREAD

**Issue by Bubbad** [Bubbad/Bubba-3D#36]
Currently the cmake file for tests requires all of the sources to be recompiled, but eg Audio and OpenGL parts can't(?) be tested in the suite. Hence they should not be a requirement for the test suite.

**Comment by SiXoS** [comment]
The controls part may also be difficult to test as it is based on keyboard/mouse/joystick input. SFML window can then also be skipped.

**Comment by DunderRoffe** [comment]
Wont be able to make it to first release

**Comment by Bubbad** [comment]
The project now has a structure for the test-suite that don't require re-compilation for tests. Instead the tests links the library. The test-suite is also scalable to add more test files.
