### ISSUE TITLE
Javadoc like documentation 

### ISSUE THREAD

**Issue by Bubbad** [Bubbad/Bubba-3D#45]
It might be good to have a javadoc-like documentation style in the project. Doxygen seems like the most used in c++ and CLion are currently implementing support for integration. Perhaps we should also discuss comment standards etc

Examples:
https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html

**Comment by SiXoS** [comment]
The controls library is documented with doxygen syntax. Maybe we could stick to the standard used there if it looks good.

**Comment by Bubbad** [comment]
Doxygen it is!
